include:
  - board: seeeduino_xiao_ble
    shield: clog_v2_left
  - board: seeeduino_xiao_ble
    shield: clog_v2_right
  - board: nrf52840_m2
    shield: settings_reset
  - board: seeeduino_xiao
    shield: settings_reset
